=== Racoom/l2glorydays/trunk/dist/gameserver/data/xml/stats/npc/spawnlist/spawn.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (spawns)*>
<!ELEMENT spawns (spawn)*>
<!ATTLIST spawns
	name CDATA #IMPLIED>
<!ELEMENT spawn (#PCDATA)>
<!ATTLIST spawn
	npcId CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	heading CDATA #IMPLIED
	delay CDATA #IMPLIED
	periodOfDay CDATA #IMPLIED>

=== Racoom/l2glorydays/trunk/dist/gameserver/data/xml/stats/npc/spawnlist/CrumaTower.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawns name="CrumaTower">
		<!-- Ридонбек -->
		<spawn npcId="33302" x="17052" y="114758" z="-3440" heading="55336" />
		<!-- Линкес -->
		<spawn npcId="33163" x="17135" y="114834" z="-3440" heading="55244" />
		<!-- Устройство перемещения -->
		<spawn npcId="33157" x="16098" y="115166" z="-11976" heading="17118" />
		<spawn npcId="33157" x="16112" y="113120" z="-11984" heading="45938" />
		<spawn npcId="33157" x="16406" y="114771" z="-9064" heading="49472" />
		<spawn npcId="33157" x="16688" y="112528" z="-11976" heading="32466" />
		<spawn npcId="33157" x="16704" y="115768" z="-11848" heading="34376" />
		<spawn npcId="33157" x="18746" y="115768" z="-11848" heading="65411" />
		<spawn npcId="33157" x="18748" y="112525" z="-11976" heading="0" />
		<spawn npcId="33157" x="19024" y="114784" z="-9064" heading="49199" />
		<spawn npcId="33157" x="19040" y="113392" z="-9064" heading="16338" />
		<spawn npcId="33157" x="19344" y="115167" z="-11976" heading="16655" />
		<spawn npcId="33157" x="19360" y="113120" z="-11984" heading="49401" />
		<!-- Эксенсио (Ивентовый Монстр) -->
		<spawn npcId="23159" x="11275" y="117228" z="-12088" heading="0" />
		<spawn npcId="23159" x="13761" y="115207" z="-9064" heading="0" />
		<spawn npcId="23159" x="13898" y="120789" z="-12080" heading="0" />
		<spawn npcId="23159" x="13982" y="111292" z="-12080" heading="0" />
		<spawn npcId="23159" x="14965" y="117279" z="-12088" heading="0" />
		<!-- Мелласио (Ивентовый Монстр) -->
		<spawn npcId="25828" x="17719" y="117300" z="-12064" heading="49264" />
		<!-- Красус (Маг Слоновой Кости) -->
		<spawn npcId="30483" x="17311" y="114079" z="-3440" heading="18664" />
		<!-- Янсен (Маг Слоновой Кости) -->
		<spawn npcId="30484" x="17636" y="114744" z="-11680" heading="6843" />
		<!-- Ромбель (Маг Слоновой Кости) -->
		<spawn npcId="30487" x="17811" y="114750" z="-11680" heading="25785" />
		<!-- Белкати (Маг Слоновой Кости) -->
		<spawn npcId="30485" x="17725" y="108220" z="-9056" heading="16384" />
		<!-- Иан (Маг Слоновой Кости) -->
		<spawn npcId="30486" x="17722" y="119749" z="-9064" heading="49152" />
	</spawns>
</list>
